### ISSUE TITLE
PW with special characters

### ISSUE THREAD

**Issue by XS666** [kspearrin/ff-password-exporter#30]
Hi there,

I use a password in Firefox 66 like

Q"W§324$(TG"§=

...and the ff-password-exporter exports to the csv-file (UTF-8):

Q""WÂ§324$(TG""Â§=

Maybe its a bug or are there limitations to the special characters?

Thanks!

**Comment by kspearrin** [comment]
Duplicate

**Comment by mickthegrit** [comment]
Dear author @kspearirrin the issue described above is two-fold: 
- when the double quote is exported, it seems it’s being escaped at the same time. 
- when the other funny symbol is exported (one after the capital W and one before the ending = ), then it gets exported with two other symbols rather than the correct one. This is another bug
