### ISSUE TITLE
error: TypeError: str.charCodeAt is not a function

### ISSUE THREAD

**Issue by vogelaar** [kspearrin/ff-password-exporter#43]
Tried this today, using Firefox 73.0 (32-bit) but got the following error:

TypeError: str.charCodeAt is not a function

I have only key4.db and logins.json

I tried it with Thunderbird, and it worked fine.

Any suggestions?

**Comment by CedricLor** [comment]
Same problem here

**Comment by Laram-H** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/58314869/75182005-89da3280-5750-11ea-8ba5-fcb4eab572cd.JPG)

Same promlem, Please answer Moderator???

**Comment by kspearrin** [comment]
Duplicate https://github.com/kspearrin/ff-password-exporter/issues/41

**Comment by Laram-H** [comment]
Duplicate #41

We've been having problems for weeks, what's the solution?

**Comment by vogelaar** [comment]
Here is a simple workaround for now using FireFox's own GUI interface to see passwords and automating it to create a csv file (needs python).  Only required 117 lines of code though.

https://github.com/lherlant/firefox_password_exporter

**Comment by DAC324** [comment]
Looks like nobody cares anymore about this program.
That's one of the big advantages of free software: You'll never know when the developers get tired of working on their projects and abandon them:(

**Comment by kspearrin** [comment]
Happy to accept a PR @DAC324

**Comment by DAC324** [comment]
@kspearrin Looks like the decryption functions need to be adapted as the database items are now encrypted using AES256 instead of 3DES / ASN1.
This means that at least the calls to forge.asn1.fromDer() need to be replaced by the AES256 equivalent.
Unfortunately, I am neither a node.js nor a crypto expert and reading through the node.js and forge documentation, I was not able to identify an appropriate solution.

**Comment by Laram-H** [comment]
You finally installed the latest version and it is working now but we waited too long:) Thanks.
